### ISSUE TITLE
Rojo/Wally: Package does not contain a `out` path

### ISSUE THREAD

**Issue by RealSimplyData** [Rimuy/GameJoy#3]
I installed the package over wally, but when starting Rojo, it exits due to an error since it is missing the `out` directory.

```
[ERROR rojo] Rojo project referred to a file using $path that could not be turned into a Roblox Instance by Rojo.
        Check that the file exists and is a file type known by Rojo.
        
        Project path: /home/sebastian/projects/roblox/[projectname]/leaderboard/Packages/_Index/rimuy_gamejoy@1.1.1/gamejoy/default.project.json
        File $path: out
```

![image](https://user-images.githubusercontent.com/30000694/151273109-a7c47c5f-6a55-4545-a79a-eae66c1ec242.png)

**Comment by Rimuy** [comment]
Looks like it didn't include three important directories. This has to do with the github action not copying those folders to the build directory. I've released a new version that fixes this project structure problem. Thank you for reporting it.
